apiVersion: v1beta
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: app-on-nginx
	env: development
    team: Frontend
    release: 1.0
spec:
  replicas: 3
  template:
    metadata:
       labels:
        app: nginx
        release: 1.0
    spec:
      containers:
        - name: nginx-app
          image: nginxdemos/hello:0.2         
          ports:
            - name: http
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    labels:
        app: nginx-app
        release: 1.0
spec:
    selector:
        app: my-nginx-app
        release: 1.0
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080


